USE [master]
GO

/****** Object:  Database [Assets_Measures]    Script Date: 10/6/2026 18:41:35 ******/
CREATE DATABASE [Assets_Measures]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Assets_Measures', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Assets_Measures.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Assets_Measures_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Assets_Measures_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Assets_Measures] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Assets_Measures].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Assets_Measures] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Assets_Measures] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Assets_Measures] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Assets_Measures] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Assets_Measures] SET ARITHABORT OFF 
GO

ALTER DATABASE [Assets_Measures] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Assets_Measures] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Assets_Measures] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Assets_Measures] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Assets_Measures] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Assets_Measures] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Assets_Measures] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Assets_Measures] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Assets_Measures] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Assets_Measures] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Assets_Measures] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Assets_Measures] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Assets_Measures] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Assets_Measures] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Assets_Measures] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Assets_Measures] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Assets_Measures] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Assets_Measures] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Assets_Measures] SET  MULTI_USER 
GO

ALTER DATABASE [Assets_Measures] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Assets_Measures] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Assets_Measures] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Assets_Measures] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Assets_Measures] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Assets_Measures] SET  READ_WRITE 
GO


