version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  # Web App - Unica entrada para el usuario final
  web-razor:
    build: ./TP_Investigacion_Microservicios
    ports:
      - "8080:8080" # Esto está bien, es tu frontend
    depends_on:
      - tp-apigateway
    networks:
      - app-network

  # Gateway - El único que necesita puerto hacia afuera
  tp-apigateway:
    build: ./TP_ApiGateway
    deploy:
      replicas: 3
    environment:
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - ms-dashboard
      - ms-login
      - ms-reporte
      - ms-oee
    networks:
      - app-network

  # Los demás servicios NO tienen la sección 'ports'
  # Docker se encarga de la comunicación interna automáticamente
  ms-login:
    build: ./Microservicio_Login
    deploy:
      replicas: 3
    environment:
      - ASPNETCORE_URLS=http://+:5080
    networks:
      - app-network

  ms-reporte:
    build: ./Microservicio_Reporte
    deploy:
      replicas: 3
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - DB_HOST=host.docker.internal
    networks:
      - app-network

  ms-dashboard:
    build: ./Microservicio_API
    deploy:
      replicas: 3
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - DB_HOST=host.docker.internal
    networks:
      - app-network

  ms-oee:
    build: ./Microservicio_OEE
    deploy:
      replicas: 3
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - DB_HOST=host.docker.internal
    networks:
      - app-network