USE [Assets_OEE]
GO

/****** Object:  Table [dbo].[asset_equipment]    Script Date: 10/6/2026 18:48:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[asset_equipment](
	[EquipmentID] [int] IDENTITY(1,1) NOT NULL,
	[NombreName] [varchar](100) NOT NULL,
	[Area] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[EquipmentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


