USE [master]
GO

/****** Object:  Database [Assets_OEE]    Script Date: 10/6/2026 18:44:00 ******/
CREATE DATABASE [Assets_OEE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Assets_OEE', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Assets_OEE.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Assets_OEE_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Assets_OEE_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Assets_OEE] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Assets_OEE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Assets_OEE] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Assets_OEE] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Assets_OEE] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Assets_OEE] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Assets_OEE] SET ARITHABORT OFF 
GO

ALTER DATABASE [Assets_OEE] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Assets_OEE] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Assets_OEE] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Assets_OEE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Assets_OEE] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Assets_OEE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Assets_OEE] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Assets_OEE] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Assets_OEE] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Assets_OEE] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Assets_OEE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Assets_OEE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Assets_OEE] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Assets_OEE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Assets_OEE] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Assets_OEE] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Assets_OEE] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Assets_OEE] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Assets_OEE] SET  MULTI_USER 
GO

ALTER DATABASE [Assets_OEE] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Assets_OEE] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Assets_OEE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Assets_OEE] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Assets_OEE] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Assets_OEE] SET  READ_WRITE 
GO


